// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRmjgDUUvlph8-msxFwwSBLNVmQ8JbSQ',
    appId: '1:432415461669:web:c4cc22372b5a3d4e8f0acc',
    messagingSenderId: '432415461669',
    projectId: 'pup-rmrs-bb1e5',
    authDomain: 'pup-rmrs-bb1e5.firebaseapp.com',
    storageBucket: 'pup-rmrs-bb1e5.appspot.com',
    measurementId: 'G-3RE22Q9SJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ2s6AvkqOM1y4JdKvsjp3Srk93tVidHM',
    appId: '1:432415461669:android:c09d1cf2d98af9b98f0acc',
    messagingSenderId: '432415461669',
    projectId: 'pup-rmrs-bb1e5',
    storageBucket: 'pup-rmrs-bb1e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIa2InDtm1iIOJ_LGhiOXgQ-_m0JnMkE',
    appId: '1:432415461669:ios:0eb55a850b48c4308f0acc',
    messagingSenderId: '432415461669',
    projectId: 'pup-rmrs-bb1e5',
    storageBucket: 'pup-rmrs-bb1e5.appspot.com',
    iosClientId: '432415461669-qpkli11bq5depemj0dnt52bo08kp0fe3.apps.googleusercontent.com',
    iosBundleId: 'com.pup.appdevelopment',
  );
}
